export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const UPDATE_CART_ITEM_QTY = 'UPDATE_CART_ITEM_QTY';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_SAVE_SHIPPING = 'CART_SAVE_SHIPPING';
export const CART_SAVE_PAYMENT = 'CART_SAVE_PAYMENT';
export const CLEAR_CART = 'CLEAR_CART';